INSERT INTO organization_units (name, unit_type)
VALUES ('Karolinska Universitetssjukhuset', 'Sjukhus');

INSERT INTO production_plans (organization_unit_id, year, care_type)
VALUES (1, 2027, 'Öppenvård');

INSERT INTO outpatient_production_rows (
  production_plan_id,
  row_label,
  kombika_pf_id,
  kombika_pf,
  section,
  cost_center,
  site,
  assignment,
  period_type,
  period_value,
  care_type,
  visit_type,
  visits,
  primary_role_category,
  secondary_role_category,
  sll_uulp,
  acute_elective,
  average_minutes_per_visit,
  drg_average,
  annual_volume,
  acute_percentage,
  elective_percentage,
  sll_percentage,
  uulp_percentage,
  drg_average_sll,
  drg_average_uulp,
  doctor_percentage,
  nurse_percentage,
  health_professional_percentage,
  other_staff_percentage,
  periodization_key_id,
  periodization_key_description,
  oo_distribution_status
)
VALUES
  (
    1,
    'Rad 01',
    'PF-001',
    'ÖPV Mottagning A',
    'Sektion A',
    'KS-1001',
    'Solna',
    'Basuppdrag',
    'day',
    '2027-03-22',
    'open_care',
    'Nybesök',
    100,
    'Läkare',
    'Sjuksköterska',
    'SLL',
    'Elektivt',
    45,
    1.20,
    5200,
    20,
    80,
    90,
    10,
    1.20,
    1.50,
    60,
    25,
    10,
    5,
    'P01',
    'Jämn fördelning över året',
    'Ej fördelad'
  ),
  (
    1,
    'Rad 02',
    'PF-002',
    'ÖPV Mottagning B',
    'Sektion B',
    'KS-1002',
    'Huddinge',
    'Tilläggsuppdrag',
    'day',
    '2027-03-22',
    'open_care',
    'Återbesök',
    75,
    'Sjuksköterska',
    'Undersköterska',
    'SLL',
    'Akut',
    35,
    1.10,
    3900,
    10,
    90,
    85,
    15,
    1.10,
    1.40,
    50,
    30,
    15,
    5,
    'P02',
    'Lägre produktion sommar',
    'Ej fördelad'
  ),
  (
    1,
    'Rad 03',
    'PF-003',
    'ÖPV Dagvård',
    'Sektion C',
    'KS-1003',
    'Solna',
    'Dagvårdsuppdrag',
    'day',
    '2027-03-23',
    'open_care',
    'Etc.',
    50,
    'Hälsoprofession',
    NULL,
    'UULP',
    'Elektivt',
    60,
    1.35,
    2600,
    5,
    95,
    80,
    20,
    1.35,
    1.60,
    40,
    35,
    20,
    5,
    'P03',
    'Högre produktion vår och höst',
    'Ej fördelad'
  );

INSERT INTO outpatient_comparison_values (
  production_plan_id,
  kombika_pf_id,
  period_type,
  period_value,
  previous_year_plan,
  r12_outcome,
  r12_presence_fouu,
  r12_presence_production,
  r12_salary_cost_per_presence,
  previous_year_outcome,
  previous_dimensioning_presence,
  source
)
VALUES
  (1, 'PF-001', 'day', '2027-03-22', 92, 88, 0.20, 1.50, 980000, 95, 1.70, 'Mockdata'),
  (1, 'PF-002', 'day', '2027-03-22', 70, 68, 0.10, 0.95, 920000, 72, 1.05, 'Mockdata'),
  (1, 'PF-003', 'day', '2027-03-23', 45, 47, 0.15, 0.90, 960000, 44, 1.10, 'Mockdata');
